version: 1.0.{build}

branches:
  only:
  - dev-vs2015

configuration:
  - Release
  # - Debug

platform:
  # - Win32
  - x64

clone_folder: c:\projects\triton

environment:
  BOOST_ROOT: C:\Libraries\boost_1_59_0

install:
  - cmd: git submodule update --init --recursive

before_build:
  - cmd: cd c:\projects\triton
  - cmd: mkdir build
  - cmd: cd build
  - cmd: echo Downloading z3...
  - ps: Start-FileDownload 'https://github.com/Z3Prover/z3/releases/download/z3-4.4.1/z3-4.4.1-x86-win.zip'
  - cmd: if "%platform%"=="Win32" 7z x z3-4.4.1-x86-win.zip
  - ps: Start-FileDownload 'https://github.com/Z3Prover/z3/releases/download/z3-4.4.1/z3-4.4.1-x64-win.zip'
  - cmd: if "%platform%"=="x64" 7z x z3-4.4.1-x64-win.zip
  - cmd: echo Downloading capstone...
  - ps: Start-FileDownload 'https://github.com/aquynh/capstone/archive/3.0.4.zip'
  - cmd: 7z x 3.0.4.zip
  - cmd: echo Building capstone...
  - cmd: cd capstone-3.0.4
  - cmd: mkdir build
  - cmd: cd build
  - cmd: if "%platform%"=="Win32" cmake .. -G "Visual Studio 14 2015"
  - cmd: if "%platform%"=="x64" cmake .. -G "Visual Studio 14 2015 Win64"
  - cmd: msbuild msvc\capstone_static\capstone_static.vcxproj /p:Configuration=%configuration% /p:Platform=%platform%
  - cmd: cd ..\..
  - cmd: echo Running cmake...
  - cmd: if "%platform%"=="Win32" cmake .. -G "Visual Studio 14 2015" -DCAPSTONE_LIBRARIES=".\capstone-3.0.4\msvc\capstone_static\%configuration%\capstone.lib" -DCAPSTONE_INCLUDE_DIRS=".\capstone-3.0.4\include" -DZ3_INCLUDE_DIRS=".\z3-4.4.1-x86-win\include" -DZ3_LIBRARIES=".\z3-4.4.1-x86-win\bin\*.lib" -DPYTHON_INCLUDE_DIRS="C:\Python27\include" -DPYTHON_LIBRARIES="C:\Python27\libs\*.lib"
  - cmd: if "%platform%"=="x64" cmake .. -G "Visual Studio 14 2015 Win64" -DCAPSTONE_LIBRARIES="D:\Codes\capstone\msvc\x64\%configuration%\capstone.lib" -DCAPSTONE_INCLUDE_DIRS=".\capstone-3.0.4\include" -DZ3_INCLUDE_DIRS=".\z3-4.4.1-x64-win\include" -DZ3_LIBRARIES=".\z3-4.4.1-x64-win\bin\*.lib" -DPYTHON_INCLUDE_DIRS="C:\Python27-x64\include" -DPYTHON_LIBRARIES="C:\Python27-x64\libs\*.lib"
  - cmd: chdir

build:
  project: c:\projects\triton\build\triton.sln

# this happens in the build directory: c:\projects\triton\build
after_build:
  - cmd: if "%platform%"=="Win32" if "%configuration%"=="Release" 7z a -t7z ..\triton.x86.release.7z ..\bin\%configuration%\triton*
  - cmd: if "%platform%"=="Win32" if "%configuration%"=="Debug" 7z a -t7z ..\triton.x86.debug.7z ..\bin\%configuration%\triton*
  - cmd: if "%platform%"=="x64" if "%configuration%"=="Release" 7z a -t7z ..\triton.x64.release.7z ..\bin\%configuration%\triton*
  - cmd: if "%platform%"=="x64" if "%configuration%"=="Debug" 7z a -t7z ..\triton.x64.release.7z ..\bin\%configuration%\triton*
  - cmd: chdir

artifacts:
  - path: triton.*.7z

# debug
on_finish:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))